# Generated by Django 3.1.3 on 2020-12-16 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.TimeField(default=datetime.datetime(2020, 12, 16, 23, 40, 43, 354261, tzinfo=utc)),
        ),
    ]
