# Generated by Django 3.1.3 on 2020-12-21 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201221_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.TimeField(default=datetime.datetime(2020, 12, 21, 15, 27, 55, 827771, tzinfo=utc)),
        ),
    ]
