# Generated by Django 3.1.3 on 2020-12-22 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201221_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(default='questionnaire1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='temp_slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 16, 23, 54, 451543, tzinfo=utc)),
        ),
    ]
