# Generated by Django 3.1.3 on 2020-12-22 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201222_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 17, 32, 10, 480469, tzinfo=utc)),
        ),
    ]
