# Generated by Django 3.1.3 on 2020-12-22 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201222_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 17, 33, 37, 472960, tzinfo=utc)),
        ),
    ]
