# Generated by Django 3.1.3 on 2020-12-22 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201222_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 18, 28, 38, 345712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lecture'), (2, 'Small group'), (3, 'Practical'), (4, 'Virtual')]),
        ),
    ]
