# Generated by Django 3.1.3 on 2020-12-24 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201224_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='resources',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 12, 41, 5, 944874, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 11, 41, 5, 944838, tzinfo=utc)),
        ),
    ]
