# Generated by Django 3.1.3 on 2020-12-24 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201224_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 13, 22, 12, 20942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='resources',
            field=models.FileField(null=True, upload_to='resources/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 12, 22, 12, 20904, tzinfo=utc)),
        ),
    ]
