# Generated by Django 3.1.3 on 2020-12-24 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201224_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='resources',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 20, 27, 2, 976401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 19, 27, 2, 976361, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.Resource.resources_folder)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
        ),
    ]
