# Generated by Django 3.1.3 on 2020-12-27 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201226_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.IntegerField(choices=[(1, 'Likert'), (2, 'Yes/No'), (3, 'Plain text')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 10, 17, 500095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 10, 17, 500041, tzinfo=utc)),
        ),
    ]
