# Generated by Django 3.1.3 on 2021-01-27 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201227_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveScaleAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.answer')),
                ('answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
            bases=('main.answer',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.IntegerField(choices=[(1, 'Likert'), (2, 'Yes/No'), (3, 'Plain text'), (4, '1 to 5')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 22, 30, 48, 216620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 21, 30, 48, 216583, tzinfo=utc)),
        ),
    ]
