# Generated by Django 3.1.3 on 2021-02-15 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivescaleanswer',
            name='answer',
            field=models.IntegerField(choices=[(1, '1 (low)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (high)')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 20, 1, 9, 860216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 1, 9, 860179, tzinfo=utc)),
        ),
    ]
