# Generated by Django 3.1.3 on 2021-03-07 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210215_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 21, 40, 22, 274904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 20, 40, 22, 274858, tzinfo=utc)),
        ),
    ]
