# Generated by Django 3.1.3 on 2021-03-20 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210307_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 14, 27, 4, 421721, tzinfo=utc)),
        ),
    ]
